name: 'LLM Review Bot'
description: 'Review Pull Requests using LLMs'
inputs:
  api_key:
    description: 'API Key for LLM'
    required: true
  azure_endpoint:
    description: 'Azure Endpoint for LLM'
    required: true
  azure_deployment:
    description: 'Azure Deployment name for LLM'
    required: true
  api_version:
    description: 'API Version for LLM'
    required: true
    default: "2023-07-01-preview"
  files:
    description: 'Files to review'
    required: true
runs:
  using: "composite"
  steps:
    - run: echo ${{ inputs.files }}
      shell: bash
