name: 'LLM Review Bot'
description: 'Review Pull Requests using LLMs'
inputs:
  file_pattern:
    description: 'Files to review'
    required: true
  additional_user_prompt:
    description: 'Additional user prompt to provide to the LLM, next to system prompt'
    default: ''
  template_name:
    description: 'A predefined instruction template to use for the LLM'
    default: ''
runs:
  using: "composite"
  steps:
    - name: 'Install Python'
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        cache: 'pip' # caching pip dependencies
    - name: Get all changed markdown files
      id: changed-markdown-files
      uses: tj-actions/changed-files@v41
      with:
        # Avoid using single or double quotes for multiline patterns
        files: ${{ inputs.file_pattern }}
    - name: "Install requirements"
      if: steps.changed-markdown-files.outputs.any_changed == 'true'
      run: pip install $GITHUB_ACTION_PATH/
      shell: bash

    - name: "Run"
      if: steps.changed-markdown-files.outputs.any_changed == 'true'
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-markdown-files.outputs.all_changed_files }}
      run: |
        python -m llm_review $ALL_CHANGED_FILES \
          --user-instruction "${{ inputs.additional_user_prompt }}" \
          --template-name "${{ inputs.template_name }}"
      shell: bash
