name: 'LLM Review Bot'
description: 'Review Pull Requests using LLMs'
inputs:
  azure_openai_api_key:
    description: 'API Key for LLM'
    required: true
  azure_openai_endpoint:
    description: 'Azure Endpoint for LLM'
    required: true
  azure_openai_deployment:
    description: 'Azure Deployment name for LLM'
    required: true
  azure_openai_api_version:
    description: 'API Version for LLM'
    required: true
    default: "2023-07-01-preview"
  file_pattern:
    description: 'Files to review'
    required: true
runs:
  using: "composite"
  steps:
    - name: 'Install Python'
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        cache: 'pip' # caching pip dependencies

    - name: "Install requirements"
      run: pip install .
      shell: bash
  
    - name: "Run"
      run: |
        python -m llm_action ${{ inputs.file_pattern }}
      shell: bash
  
