name: 'LLM Review Bot'
description: 'Review Pull Requests using LLMs'
inputs:
  file_pattern:
    description: 'Files to review'
    required: true
  additional_user_prompt:
    description: 'Additional user prompt to provide to the LLM, next to system prompt'
    default: ''
runs:
  using: "composite"
  steps:
    - name: 'Install Python'
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        cache: 'pip' # caching pip dependencies

    - name: "Install requirements"
      run: pip install .
      shell: bash
  
    - name: "Run"
      run: |
        python -m llm_action ${{ inputs.file_pattern }} --user-instructions "${{ inputs.additional_user_prompt }}"
      shell: bash
  
