on: [push]

jobs:
  review:
    runs-on: ubuntu-latest
    name: Review
    steps:
      - uses: actions/checkout@v4
      - uses: timotk/github-llm-action@v1
        name: Review python code
        with:
          file_pattern: "examples/*.py"
          additional_user_prompt: "Make sure the code is pythonic"
        env:
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
          AZURE_OPENAI_ENDPOINT: "https://xebia-openai-us.openai.azure.com/"
          AZURE_OPENAI_DEPLOYMENT: "gpt-35-turbo-us"
          AZURE_OPENAI_API_VERSION: "2023-07-01-preview"
      - uses: timotk/github-llm-action@v1
        name: Emojify a song
        with:
          file_pattern: "examples/song.txt"
          additional_user_prompt: "Suggest an emoji for each line, nothing else"
        env:
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
          AZURE_OPENAI_ENDPOINT: "https://xebia-openai-us.openai.azure.com/"
          AZURE_OPENAI_DEPLOYMENT: "gpt-35-turbo-us"
          AZURE_OPENAI_API_VERSION: "2023-07-01-preview"
